
package com.oracle.xmlns.oxp.service.publicreportservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PublicReportService", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicReportService {


    /**
     * 
     * @param bipSessionToken
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "logoutReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "logout", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.LogoutResponse")
    public boolean logout(
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception
    ;

    /**
     * 
     * @param adminUsername
     * @param username
     * @param adminPassword
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "impersonateReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "impersonate", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.Impersonate")
    @ResponseWrapper(localName = "impersonateResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.ImpersonateResponse")
    public String impersonate(
        @WebParam(name = "adminUsername", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String adminUsername,
        @WebParam(name = "adminPassword", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String adminPassword,
        @WebParam(name = "username", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String username)
        throws AccessDeniedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param reportRequest
     * @param password
     * @return
     *     returns java.util.List<com.oracle.xmlns.oxp.service.publicreportservice.ParamNameValue>
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportParametersReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getReportParameters", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetReportParameters")
    @ResponseWrapper(localName = "getReportParametersResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetReportParametersResponse")
    public List<ParamNameValue> getReportParameters(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        ReportRequest reportRequest,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateFileName
     * @param folderAbsolutePathURL
     * @param templateData
     * @param xliffData
     * @param xliffFileName
     * @param updateFlag
     * @param password
     * @param reportName
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "createReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "createReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.CreateReport")
    @ResponseWrapper(localName = "createReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.CreateReportResponse")
    public String createReport(
        @WebParam(name = "reportName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportName,
        @WebParam(name = "folderAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePathURL,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateFileName,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] templateData,
        @WebParam(name = "XLIFFFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String xliffFileName,
        @WebParam(name = "XLIFFData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] xliffData,
        @WebParam(name = "updateFlag", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        boolean updateFlag,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "deleteReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteReport")
    @ResponseWrapper(localName = "deleteReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteReportResponse")
    public boolean deleteReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "validateLoginReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "validateLogin", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.ValidateLogin")
    @ResponseWrapper(localName = "validateLoginResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.ValidateLoginResponse")
    public boolean validateLogin(
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password);

    /**
     * 
     * @param userID
     * @param password
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "loginReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "login", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.LoginResponse")
    public String login(
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getSecurityModelReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getSecurityModel", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetSecurityModel")
    @ResponseWrapper(localName = "getSecurityModelResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetSecurityModelResponse")
    public String getSecurityModel();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "getBIPHTTPSessionIntervalReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getBIPHTTPSessionInterval", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetBIPHTTPSessionInterval")
    @ResponseWrapper(localName = "getBIPHTTPSessionIntervalResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetBIPHTTPSessionIntervalResponse")
    public int getBIPHTTPSessionInterval();

    /**
     * 
     * @param userID
     * @param reportRequest
     * @param password
     * @return
     *     returns com.oracle.xmlns.oxp.service.publicreportservice.ReportResponse
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "runReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "runReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.RunReport")
    @ResponseWrapper(localName = "runReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.RunReportResponse")
    public ReportResponse runReport(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        ReportRequest reportRequest,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRequest
     * @param bipSessionToken
     * @return
     *     returns com.oracle.xmlns.oxp.service.publicreportservice.ReportResponse
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "runReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "runReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.RunReportInSession")
    @ResponseWrapper(localName = "runReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.RunReportInSessionResponse")
    public ReportResponse runReportInSession(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        ReportRequest reportRequest,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns com.oracle.xmlns.oxp.service.publicreportservice.ReportDefinition
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getReportDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetReportDefinition")
    @ResponseWrapper(localName = "getReportDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetReportDefinitionResponse")
    public ReportDefinition getReportDefinition(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns com.oracle.xmlns.oxp.service.publicreportservice.ReportDefinition
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getReportDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetReportDefinitionInSession")
    @ResponseWrapper(localName = "getReportDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetReportDefinitionInSessionResponse")
    public ReportDefinition getReportDefinitionInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRequest
     * @param bipSessionToken
     * @return
     *     returns java.util.List<com.oracle.xmlns.oxp.service.publicreportservice.ParamNameValue>
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportParametersInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getReportParametersInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetReportParametersInSession")
    @ResponseWrapper(localName = "getReportParametersInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetReportParametersInSessionResponse")
    public List<ParamNameValue> getReportParametersInSession(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        ReportRequest reportRequest,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param folderAbsolutePath
     * @param password
     * @return
     *     returns java.util.List<com.oracle.xmlns.oxp.service.publicreportservice.ItemData>
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getFolderContentsReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getFolderContents", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetFolderContents")
    @ResponseWrapper(localName = "getFolderContentsResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetFolderContentsResponse")
    public List<ItemData> getFolderContents(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param folderAbsolutePath
     * @return
     *     returns java.util.List<com.oracle.xmlns.oxp.service.publicreportservice.ItemData>
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getFolderContentsInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getFolderContentsInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetFolderContentsInSession")
    @ResponseWrapper(localName = "getFolderContentsInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetFolderContentsInSessionResponse")
    public List<ItemData> getFolderContentsInSession(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param scheduleRequest
     * @param password
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "scheduleReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "scheduleReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.ScheduleReport")
    @ResponseWrapper(localName = "scheduleReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.ScheduleReportResponse")
    public String scheduleReport(
        @WebParam(name = "scheduleRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        ScheduleRequest scheduleRequest,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param scheduleRequest
     * @param bipSessionToken
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "scheduleReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "scheduleReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.ScheduleReportInSession")
    @ResponseWrapper(localName = "scheduleReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.ScheduleReportInSessionResponse")
    public String scheduleReportInSession(
        @WebParam(name = "scheduleRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        ScheduleRequest scheduleRequest,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "hasReportAccessReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "hasReportAccess", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.HasReportAccess")
    @ResponseWrapper(localName = "hasReportAccessResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.HasReportAccessResponse")
    public boolean hasReportAccess(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws InvalidParametersException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     */
    @WebMethod
    @WebResult(name = "hasReportAccessInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "hasReportAccessInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.HasReportAccessInSession")
    @ResponseWrapper(localName = "hasReportAccessInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.HasReportAccessInSessionResponse")
    public boolean hasReportAccessInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws InvalidParametersException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "isReportExistReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "isReportExist", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.IsReportExist")
    @ResponseWrapper(localName = "isReportExistResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.IsReportExistResponse")
    public boolean isReportExist(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "isReportExistInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "isReportExistInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.IsReportExistInSession")
    @ResponseWrapper(localName = "isReportExistInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.IsReportExistInSessionResponse")
    public boolean isReportExistInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param folderAbsolutePath
     * @param password
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "isFolderExistReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "isFolderExist", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.IsFolderExist")
    @ResponseWrapper(localName = "isFolderExistResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.IsFolderExistResponse")
    public boolean isFolderExist(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param folderAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "isFolderExistInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "isFolderExistInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.IsFolderExistInSession")
    @ResponseWrapper(localName = "isFolderExistInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.IsFolderExistInSessionResponse")
    public boolean isFolderExistInSession(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param scheduledJobID
     * @return
     *     returns com.oracle.xmlns.oxp.service.publicreportservice.JobStatus
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledReportStatusReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getScheduledReportStatus", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetScheduledReportStatus")
    @ResponseWrapper(localName = "getScheduledReportStatusResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetScheduledReportStatusResponse")
    public JobStatus getScheduledReportStatus(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param scheduledJobID
     * @return
     *     returns com.oracle.xmlns.oxp.service.publicreportservice.JobStatus
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledReportStatusInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getScheduledReportStatusInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetScheduledReportStatusInSession")
    @ResponseWrapper(localName = "getScheduledReportStatusInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetScheduledReportStatusInSessionResponse")
    public JobStatus getScheduledReportStatusInSession(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param scheduledJobIDs
     * @param password
     * @return
     *     returns java.util.List<com.oracle.xmlns.oxp.service.publicreportservice.JobStatus>
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getListOfScheduledReportsStatusReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getListOfScheduledReportsStatus", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetListOfScheduledReportsStatus")
    @ResponseWrapper(localName = "getListOfScheduledReportsStatusResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetListOfScheduledReportsStatusResponse")
    public List<JobStatus> getListOfScheduledReportsStatus(
        @WebParam(name = "scheduledJobIDs", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        List<String> scheduledJobIDs,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param scheduledJobIDs
     * @return
     *     returns java.util.List<com.oracle.xmlns.oxp.service.publicreportservice.JobStatus>
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getListOfScheduledReportsStatusInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getListOfScheduledReportsStatusInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetListOfScheduledReportsStatusInSession")
    @ResponseWrapper(localName = "getListOfScheduledReportsStatusInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetListOfScheduledReportsStatusInSessionResponse")
    public List<JobStatus> getListOfScheduledReportsStatusInSession(
        @WebParam(name = "scheduledJobIDs", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        List<String> scheduledJobIDs,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param viewByFilter
     * @param password
     * @param scheduledJobID
     * @return
     *     returns java.util.List<com.oracle.xmlns.oxp.service.publicreportservice.JobInfo>
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledReportInfoReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getScheduledReportInfo", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetScheduledReportInfo")
    @ResponseWrapper(localName = "getScheduledReportInfoResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetScheduledReportInfoResponse")
    public List<JobInfo> getScheduledReportInfo(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password,
        @WebParam(name = "viewByFilter", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String viewByFilter)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param viewByFilter
     * @param bipSessionToken
     * @param scheduledJobID
     * @return
     *     returns java.util.List<com.oracle.xmlns.oxp.service.publicreportservice.JobInfo>
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledReportInfoInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getScheduledReportInfoInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetScheduledReportInfoInSession")
    @ResponseWrapper(localName = "getScheduledReportInfoInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetScheduledReportInfoInSessionResponse")
    public List<JobInfo> getScheduledReportInfoInSession(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "viewByFilter", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String viewByFilter)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param viewByFilter
     * @param password
     * @param scheduledJobID
     * @param bDownloadReport
     * @return
     *     returns java.util.List<com.oracle.xmlns.oxp.service.publicreportservice.JobHistoryInfo>
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledReportHistoryInfoReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getScheduledReportHistoryInfo", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetScheduledReportHistoryInfo")
    @ResponseWrapper(localName = "getScheduledReportHistoryInfoResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetScheduledReportHistoryInfoResponse")
    public List<JobHistoryInfo> getScheduledReportHistoryInfo(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password,
        @WebParam(name = "viewByFilter", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String viewByFilter,
        @WebParam(name = "bDownloadReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        boolean bDownloadReport)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param viewByFilter
     * @param bipSessionToken
     * @param scheduledJobID
     * @param bDownloadReport
     * @return
     *     returns java.util.List<com.oracle.xmlns.oxp.service.publicreportservice.JobHistoryInfo>
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "getScheduledReportHistoryInfoInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "getScheduledReportHistoryInfoInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetScheduledReportHistoryInfoInSession")
    @ResponseWrapper(localName = "getScheduledReportHistoryInfoInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.GetScheduledReportHistoryInfoInSessionResponse")
    public List<JobHistoryInfo> getScheduledReportHistoryInfoInSession(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "viewByFilter", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String viewByFilter,
        @WebParam(name = "bDownloadReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        boolean bDownloadReport)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param scheduledJobID
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "suspendScheduledReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "suspendScheduledReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.SuspendScheduledReport")
    @ResponseWrapper(localName = "suspendScheduledReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.SuspendScheduledReportResponse")
    public boolean suspendScheduledReport(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param scheduledJobID
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "suspendScheduledReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "suspendScheduledReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.SuspendScheduledReportInSession")
    @ResponseWrapper(localName = "suspendScheduledReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.SuspendScheduledReportInSessionResponse")
    public boolean suspendScheduledReportInSession(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param scheduledJobID
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "resumeScheduledReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "resumeScheduledReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.ResumeScheduledReport")
    @ResponseWrapper(localName = "resumeScheduledReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.ResumeScheduledReportResponse")
    public boolean resumeScheduledReport(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param scheduledJobID
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "resumeScheduledReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "resumeScheduledReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.ResumeScheduledReportInSession")
    @ResponseWrapper(localName = "resumeScheduledReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.ResumeScheduledReportInSessionResponse")
    public boolean resumeScheduledReportInSession(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param scheduledJobID
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteScheduledReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "deleteScheduledReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteScheduledReport")
    @ResponseWrapper(localName = "deleteScheduledReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteScheduledReportResponse")
    public boolean deleteScheduledReport(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param scheduledJobID
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteScheduledReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "deleteScheduledReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteScheduledReportInSession")
    @ResponseWrapper(localName = "deleteScheduledReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteScheduledReportInSessionResponse")
    public boolean deleteScheduledReportInSession(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param scheduledJobID
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteScheduledReportHistoryReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "deleteScheduledReportHistory", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteScheduledReportHistory")
    @ResponseWrapper(localName = "deleteScheduledReportHistoryResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteScheduledReportHistoryResponse")
    public boolean deleteScheduledReportHistory(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param scheduledJobID
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteScheduledReportHistoryInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "deleteScheduledReportHistoryInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteScheduledReportHistoryInSession")
    @ResponseWrapper(localName = "deleteScheduledReportHistoryInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteScheduledReportHistoryInSessionResponse")
    public boolean deleteScheduledReportHistoryInSession(
        @WebParam(name = "scheduledJobID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String scheduledJobID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateFileName
     * @param folderAbsolutePathURL
     * @param templateData
     * @param xliffData
     * @param xliffFileName
     * @param bipSessionToken
     * @param updateFlag
     * @param reportName
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "createReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "createReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.CreateReportInSession")
    @ResponseWrapper(localName = "createReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.CreateReportInSessionResponse")
    public String createReportInSession(
        @WebParam(name = "reportName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportName,
        @WebParam(name = "folderAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePathURL,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateFileName,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] templateData,
        @WebParam(name = "XLIFFFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String xliffFileName,
        @WebParam(name = "XLIFFData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] xliffData,
        @WebParam(name = "updateFlag", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        boolean updateFlag,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param newReportDefn
     * @param password
     * @param reportAbsPath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateReportDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "updateReportDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UpdateReportDefinition")
    @ResponseWrapper(localName = "updateReportDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UpdateReportDefinitionResponse")
    public boolean updateReportDefinition(
        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsPath,
        @WebParam(name = "newReportDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        ReportDefinition newReportDefn,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param newReportDefn
     * @param reportAbsPath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateReportDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "updateReportDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UpdateReportDefinitionInSession")
    @ResponseWrapper(localName = "updateReportDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UpdateReportDefinitionInSessionResponse")
    public boolean updateReportDefinitionInSession(
        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsPath,
        @WebParam(name = "newReportDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        ReportDefinition newReportDefn,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param folderAbsolutePath
     * @param password
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "createReportFolderReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "createReportFolder", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.CreateReportFolder")
    @ResponseWrapper(localName = "createReportFolderResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.CreateReportFolderResponse")
    public String createReportFolder(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param folderAbsolutePath
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "createReportFolderInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "createReportFolderInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.CreateReportFolderInSession")
    @ResponseWrapper(localName = "createReportFolderInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.CreateReportFolderInSessionResponse")
    public String createReportFolderInSession(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateFileName
     * @param templateData
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "uploadTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UploadTemplateForReport")
    @ResponseWrapper(localName = "uploadTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UploadTemplateForReportResponse")
    public boolean uploadTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateFileName,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] templateData,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateFileName
     * @param templateData
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadTemplateForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "uploadTemplateForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UploadTemplateForReportInSession")
    @ResponseWrapper(localName = "uploadTemplateForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UploadTemplateForReportInSessionResponse")
    public boolean uploadTemplateForReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateFileName,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] templateData,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateFileName
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "removeTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "removeTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.RemoveTemplateForReport")
    @ResponseWrapper(localName = "removeTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.RemoveTemplateForReportResponse")
    public boolean removeTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateFileName,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateFileName
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "removeTemplateForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "removeTemplateForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.RemoveTemplateForReportInSession")
    @ResponseWrapper(localName = "removeTemplateForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.RemoveTemplateForReportInSessionResponse")
    public boolean removeTemplateForReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String templateFileName,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRawDataChunk
     * @param fileID
     * @param reportDataChunk
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadReportDataChunkReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "uploadReportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UploadReportDataChunk")
    @ResponseWrapper(localName = "uploadReportDataChunkResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UploadReportDataChunkResponse")
    public String uploadReportDataChunk(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String fileID,
        @WebParam(name = "reportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] reportDataChunk,
        @WebParam(name = "reportRawDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportRawDataChunk)
        throws OperationFailedException_Exception
    ;

    /**
     * 
     * @param fileID
     * @param beginIdx
     * @param size
     * @return
     *     returns com.oracle.xmlns.oxp.service.publicreportservice.ReportDataChunk
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadReportDataChunkReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "downloadReportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DownloadReportDataChunk")
    @ResponseWrapper(localName = "downloadReportDataChunkResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DownloadReportDataChunkResponse")
    public ReportDataChunk downloadReportDataChunk(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String fileID,
        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        int beginIdx,
        @WebParam(name = "size", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        int size)
        throws OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param reportZippedData
     * @param folderAbsolutePathURL
     * @param password
     * @param reportName
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "uploadReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UploadReport")
    @ResponseWrapper(localName = "uploadReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UploadReportResponse")
    public String uploadReport(
        @WebParam(name = "reportName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportName,
        @WebParam(name = "folderAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePathURL,
        @WebParam(name = "reportZippedData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] reportZippedData,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportZippedData
     * @param folderAbsolutePathURL
     * @param bipSessionToken
     * @param reportName
     * @return
     *     returns java.lang.String
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "uploadReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UploadReportInSession")
    @ResponseWrapper(localName = "uploadReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.UploadReportInSessionResponse")
    public String uploadReportInSession(
        @WebParam(name = "reportName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportName,
        @WebParam(name = "folderAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePathURL,
        @WebParam(name = "reportZippedData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] reportZippedData,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "deleteReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteReportInSession")
    @ResponseWrapper(localName = "deleteReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteReportInSessionResponse")
    public boolean deleteReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param folderAbsolutePath
     * @param password
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteFolderReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "deleteFolder", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteFolder")
    @ResponseWrapper(localName = "deleteFolderResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteFolderResponse")
    public boolean deleteFolder(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param folderAbsolutePath
     * @return
     *     returns boolean
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteFolderInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "deleteFolderInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteFolderInSession")
    @ResponseWrapper(localName = "deleteFolderInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DeleteFolderInSessionResponse")
    public boolean deleteFolderInSession(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String folderAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "downloadReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DownloadReport")
    @ResponseWrapper(localName = "downloadReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DownloadReportResponse")
    public byte[] downloadReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws AccessDeniedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    @RequestWrapper(localName = "downloadReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DownloadReportInSession")
    @ResponseWrapper(localName = "downloadReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.oracle.xmlns.oxp.service.publicreportservice.DownloadReportInSessionResponse")
    public byte[] downloadReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String reportAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

}
